export const advisors = [
    { "id": 1, "name": "Physics Advisor", "email": "advisor.physics@iyte.edu.tr", "type": "Professor", "departmentId": 1, "password": "password_advisor_1" },
    { "id": 2, "name": "Photonics Advisor", "email": "advisor.photonics@iyte.edu.tr", "type": "Professor", "departmentId": 2, "password": "password_advisor_2" },
    { "id": 3, "name": "Chemistry Advisor", "email": "advisor.chemistry@iyte.edu.tr", "type": "Professor", "departmentId": 3, "password": "password_advisor_3" },
    { "id": 4, "name": "Mathematics Advisor", "email": "advisor.mathematics@iyte.edu.tr", "type": "Professor", "departmentId": 4, "password": "password_advisor_4" },
    { "id": 5, "name": "MolBioGen Advisor", "email": "advisor.molbiogen@iyte.edu.tr", "type": "Professor", "departmentId": 5, "password": "password_advisor_5" },
    { "id": 6, "name": "CompEng Advisor", "email": "advisor.compeng@iyte.edu.tr", "type": "Professor", "departmentId": 6, "password": "password_advisor_6" },
    { "id": 7, "name": "BioEng Advisor", "email": "advisor.bioeng@iyte.edu.tr", "type": "Professor", "departmentId": 7, "password": "password_advisor_7" },
    { "id": 8, "name": "EnvEng Advisor", "email": "advisor.enveng@iyte.edu.tr", "type": "Professor", "departmentId": 8, "password": "password_advisor_8" },
    { "id": 9, "name": "EnergySysEng Advisor", "email": "advisor.energysyseng@iyte.edu.tr", "type": "Professor", "departmentId": 9, "password": "password_advisor_9" },
    { "id": 10, "name": "EEE Advisor", "email": "advisor.eee@iyte.edu.tr", "type": "Professor", "departmentId": 10, "password": "password_advisor_10" },
    { "id": 11, "name": "FoodEng Advisor", "email": "advisor.foodeng@iyte.edu.tr", "type": "Professor", "departmentId": 11, "password": "password_advisor_11" },
    { "id": 12, "name": "CivilEng Advisor", "email": "advisor.civileng@iyte.edu.tr", "type": "Professor", "departmentId": 12, "password": "password_advisor_12" },
    { "id": 13, "name": "ChemEng Advisor", "email": "advisor.chemeng@iyte.edu.tr", "type": "Professor", "departmentId": 13, "password": "password_advisor_13" },
    { "id": 14, "name": "MechEng Advisor", "email": "advisor.mecheng@iyte.edu.tr", "type": "Professor", "departmentId": 14, "password": "password_advisor_14" },
    { "id": 15, "name": "MatSciEng Advisor", "email": "advisor.matscieng@iyte.edu.tr", "type": "Professor", "departmentId": 15, "password": "password_advisor_15" },
    { "id": 16, "name": "IndDesign Advisor", "email": "advisor.inddesign@iyte.edu.tr", "type": "Professor", "departmentId": 16, "password": "password_advisor_16" },
    { "id": 17, "name": "Arch Advisor", "email": "advisor.arch@iyte.edu.tr", "type": "Professor", "departmentId": 17, "password": "password_advisor_17" },
    { "id": 18, "name": "CityPlan Advisor", "email": "advisor.cityplan@iyte.edu.tr", "type": "Professor", "departmentId": 18, "password": "password_advisor_18" }
  ]