export const advisors = [
  {"id":1,"name":"Physics Advisor 1","email":"advisor.physics1@iyte.edu.tr","departmentId":1,"password":"password_advisor_1"},
  {"id":2,"name":"Physics Advisor 2","email":"advisor.physics2@iyte.edu.tr","departmentId":1,"password":"password_advisor_2"},
  {"id":3,"name":"Physics Advisor 3","email":"advisor.physics3@iyte.edu.tr","departmentId":1,"password":"password_advisor_3"},
  {"id":4,"name":"Photonics Advisor 1","email":"advisor.photonics1@iyte.edu.tr","departmentId":2,"password":"password_advisor_4"},
  {"id":5,"name":"Photonics Advisor 2","email":"advisor.photonics2@iyte.edu.tr","departmentId":2,"password":"password_advisor_5"},
  {"id":6,"name":"Photonics Advisor 3","email":"advisor.photonics3@iyte.edu.tr","departmentId":2,"password":"password_advisor_6"},
  {"id":7,"name":"Chemistry Advisor 1","email":"advisor.chemistry1@iyte.edu.tr","departmentId":3,"password":"password_advisor_7"},
  {"id":8,"name":"Chemistry Advisor 2","email":"advisor.chemistry2@iyte.edu.tr","departmentId":3,"password":"password_advisor_8"},
  {"id":9,"name":"Chemistry Advisor 3","email":"advisor.chemistry3@iyte.edu.tr","departmentId":3,"password":"password_advisor_9"},
  {"id":10,"name":"Mathematics Advisor 1","email":"advisor.mathematics1@iyte.edu.tr","departmentId":4,"password":"password_advisor_10"},
  {"id":11,"name":"Mathematics Advisor 2","email":"advisor.mathematics2@iyte.edu.tr","departmentId":4,"password":"password_advisor_11"},
  {"id":12,"name":"Mathematics Advisor 3","email":"advisor.mathematics3@iyte.edu.tr","departmentId":4,"password":"password_advisor_12"},
  {"id":13,"name":"MolBioGen Advisor 1","email":"advisor.molbiogen1@iyte.edu.tr","departmentId":5,"password":"password_advisor_13"},
  {"id":14,"name":"MolBioGen Advisor 2","email":"advisor.molbiogen2@iyte.edu.tr","departmentId":5,"password":"password_advisor_14"},
  {"id":15,"name":"MolBioGen Advisor 3","email":"advisor.molbiogen3@iyte.edu.tr","departmentId":5,"password":"password_advisor_15"},
  {"id":16,"name":"Buket Erşahin","email":"buketoksuzoglu@iyte.edu.tr","departmentId":6,"password":"password_advisor_16"},
  {"id":17,"name":"Samet Tenekeci","email":"samettenekeci@iyte.edu.tr","departmentId":6,"password":"password_advisor_17"},
  {"id":18,"name":"Onur Demirörs","email":"onurdemirors@iyte.edu.tr","departmentId":6,"password":"password_advisor_18"},
  {"id":19,"name":"BioEng Advisor 1","email":"advisor.bioeng1@iyte.edu.tr","departmentId":7,"password":"password_advisor_19"},
  {"id":20,"name":"BioEng Advisor 2","email":"advisor.bioeng2@iyte.edu.tr","departmentId":7,"password":"password_advisor_20"},
  {"id":21,"name":"BioEng Advisor 3","email":"advisor.bioeng3@iyte.edu.tr","departmentId":7,"password":"password_advisor_21"},
  {"id":22,"name":"EnvEng Advisor 1","email":"advisor.enveng1@iyte.edu.tr","departmentId":8,"password":"password_advisor_22"},
  {"id":23,"name":"EnvEng Advisor 2","email":"advisor.enveng2@iyte.edu.tr","departmentId":8,"password":"password_advisor_23"},
  {"id":24,"name":"EnvEng Advisor 3","email":"advisor.enveng3@iyte.edu.tr","departmentId":8,"password":"password_advisor_24"},
  {"id":25,"name":"EnergySysEng Advisor 1","email":"advisor.energysyseng1@iyte.edu.tr","departmentId":9,"password":"password_advisor_25"},
  {"id":26,"name":"EnergySysEng Advisor 2","email":"advisor.energysyseng2@iyte.edu.tr","departmentId":9,"password":"password_advisor_26"},
  {"id":27,"name":"EnergySysEng Advisor 3","email":"advisor.energysyseng3@iyte.edu.tr","departmentId":9,"password":"password_advisor_27"},
  {"id":28,"name":"EEE Advisor 1","email":"advisor.eee1@iyte.edu.tr","departmentId":10,"password":"password_advisor_28"},
  {"id":29,"name":"EEE Advisor 2","email":"advisor.eee2@iyte.edu.tr","departmentId":10,"password":"password_advisor_29"},
  {"id":30,"name":"EEE Advisor 3","email":"advisor.eee3@iyte.edu.tr","departmentId":10,"password":"password_advisor_30"},
  {"id":31,"name":"FoodEng Advisor 1","email":"advisor.foodeng1@iyte.edu.tr","departmentId":11,"password":"password_advisor_31"},
  {"id":32,"name":"FoodEng Advisor 2","email":"advisor.foodeng2@iyte.edu.tr","departmentId":11,"password":"password_advisor_32"},
  {"id":33,"name":"FoodEng Advisor 3","email":"advisor.foodeng3@iyte.edu.tr","departmentId":11,"password":"password_advisor_33"},
  {"id":34,"name":"CivilEng Advisor 1","email":"advisor.civileng1@iyte.edu.tr","departmentId":12,"password":"password_advisor_34"},
  {"id":35,"name":"CivilEng Advisor 2","email":"advisor.civileng2@iyte.edu.tr","departmentId":12,"password":"password_advisor_35"},
  {"id":36,"name":"CivilEng Advisor 3","email":"advisor.civileng3@iyte.edu.tr","departmentId":12,"password":"password_advisor_36"},
  {"id":37,"name":"ChemEng Advisor 1","email":"advisor.chemeng1@iyte.edu.tr","departmentId":13,"password":"password_advisor_37"},
  {"id":38,"name":"ChemEng Advisor 2","email":"advisor.chemeng2@iyte.edu.tr","departmentId":13,"password":"password_advisor_38"},
  {"id":39,"name":"ChemEng Advisor 3","email":"advisor.chemeng3@iyte.edu.tr","departmentId":13,"password":"password_advisor_39"},
  {"id":40,"name":"MechEng Advisor 1","email":"advisor.mecheng1@iyte.edu.tr","departmentId":14,"password":"password_advisor_40"},
  {"id":41,"name":"MechEng Advisor 2","email":"advisor.mecheng2@iyte.edu.tr","departmentId":14,"password":"password_advisor_41"},
  {"id":42,"name":"MechEng Advisor 3","email":"advisor.mecheng3@iyte.edu.tr","departmentId":14,"password":"password_advisor_42"},
  {"id":43,"name":"MatSciEng Advisor 1","email":"advisor.matscieng1@iyte.edu.tr","departmentId":15,"password":"password_advisor_43"},
  {"id":44,"name":"MatSciEng Advisor 2","email":"advisor.matscieng2@iyte.edu.tr","departmentId":15,"password":"password_advisor_44"},
  {"id":45,"name":"MatSciEng Advisor 3","email":"advisor.matscieng3@iyte.edu.tr","departmentId":15,"password":"password_advisor_45"},
  {"id":46,"name":"IndDesign Advisor 1","email":"advisor.inddesign1@iyte.edu.tr","departmentId":16,"password":"password_advisor_46"},
  {"id":47,"name":"IndDesign Advisor 2","email":"advisor.inddesign2@iyte.edu.tr","departmentId":16,"password":"password_advisor_47"},
  {"id":48,"name":"IndDesign Advisor 3","email":"advisor.inddesign3@iyte.edu.tr","departmentId":16,"password":"password_advisor_48"},
  {"id":49,"name":"Architecture Advisor 1","email":"advisor.arch1@iyte.edu.tr","departmentId":17,"password":"password_advisor_49"},
  {"id":50,"name":"Architecture Advisor 2","email":"advisor.arch2@iyte.edu.tr","departmentId":17,"password":"password_advisor_50"},
  {"id":51,"name":"Architecture Advisor 3","email":"advisor.arch3@iyte.edu.tr","departmentId":17,"password":"password_advisor_51"},
  {"id":52,"name":"CityPlan Advisor 1","email":"advisor.cityplan1@iyte.edu.tr","departmentId":18,"password":"password_advisor_52"},
  {"id":53,"name":"CityPlan Advisor 2","email":"advisor.cityplan2@iyte.edu.tr","departmentId":18,"password":"password_advisor_53"},
  {"id":54,"name":"CityPlan Advisor 3","email":"advisor.cityplan3@iyte.edu.tr","departmentId":18,"password":"password_advisor_54"}
]